export default function physicsocrselectcollect() {
    const physicsocrtitles = ['A-Level Physics A  Modelling Physics (H556/01)', 'A-Level Physics A  Exploring Physics (H556/02)', 'A-Level Physics A  Unified Physics (H556/03)', 'AS Physics A  Breath in Physics (H156/01)', 'AS Physics A  Depth in Physics (H156/02)', 'A-Level Physics B (Advancing Physics)  Fundamentals of Physics (H557/01)', 'A-Level Physics B (Advancing Physics)  Scientific Literacy in Physics (H557/02)', 'A-Level Physics B (Advancing Physics)  Practical Skills in Physics (H557/03)', 'AS Physics B (Advancing Physics)  Foundations of Physics (H157/01)', 'AS Physics B (Advancing Physics)  Physics in Depth (H157/02)', 'A-Level Physics A  Modelling Physics (H556/01)', 'A-Level Physics A  Exploring Physics (H556/02)', 'A-Level Physics A  Unified Physics (H556/03)', 'AS Physics A  Breath in Physics (H156/01)', 'AS Physics A  Depth in Physics (H156/02)', 'A-Level Physics B (Advancing Physics)  Fundamentals of Physics (H557/01)', 'A-Level Physics B (Advancing Physics)  Scientific Literacy in Physics (H557/02)', 'A-Level Physics B (Advancing Physics)  Practical Skills in Physics (H557/03)', 'AS Physics B (Advancing Physics)  Foundations of Physics (H157/01)', 'AS Physics B (Advancing Physics)  Physics in Depth (H157/02)', 'A-Level Physics A  Modelling Physics (H556/01)', 'A-Level Physics A  Exploring Physics (H556/02)', 'A-Level Physics A  Unified Physics (H556/03)', 'AS Physics A  Breath in Physics (H156/01)', 'AS Physics A  Depth in Physics (H156/02)', 'A-Level Physics B (Advancing Physics)  Fundamentals of Physics (H557/01)', 'A-Level Physics B (Advancing Physics)  Scientific Literacy in Physics (H557/02)', 'A-Level Physics B (Advancing Physics)  Practical Skills in Physics (H557/03)', 'AS Physics B (Advancing Physics)  Foundations of Physics (H157/01)', 'AS Physics B (Advancing Physics)  Physics in Depth (H157/02)', 'A-Level Physics A  Modelling Physics (H556/01)', 'A-Level Physics A  Exploring Physics (H556/02)', 'A-Level Physics A  Unified Physics (H556/03)', 'A-Level Physics B (Advancing Physics)  Fundamentals of Physics (H557/01)', 'A-Level Physics B (Advancing Physics)  Scientific Literacy in Physics (H557/02)', 'A-Level Physics B (Advancing Physics)  Practical Skills in Physics (H557/03)']
    const  physicsocrselect = []
    for (let i = 0; i< physicsocrtitles.length; i++) { 
        physicsocrselect.push({'label':`${physicsocrtitles[i]}`,'value':i})

    }
    return physicsocrselect
    

}